---
title: "Did Texas A&M have the most disappointing college football season of the 2000s?"
author: "Ryan Kenney"
date: '2022-12-04'
categories: [CFB, code, analysis]
image: ""
format: 
  html:
    code-fold: true
---

Texas A&M is making all kinds of college football history in 2022.

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(gt)
library(cowplot)

bama00 <- read.csv("Bama00.csv")
oregst01 <- read.csv("OregSt01.csv")
flast01 <- read.csv("FlaSt01.csv")
nw01 <- read.csv("NW01.csv")
missst01 <- read.csv("MissSt01.csv")
nu02 <- read.csv("NU02.csv")
auburn03 <- read.csv("Auburn03.csv")
kst04 <- read.csv("KSt04.csv")
mich05 <- read.csv("Mich05.csv")
tenn05 <- read.csv("Tenn05.csv")
nd06 <- read.csv("ND06.csv")
flast06 <- read.csv("FlaSt06.csv")
mich07 <- read.csv("Mich07.csv")
louisville07 <- read.csv("Louisville07.csv")
ugaandauburn08 <- read.csv("UGAandAuburn08.csv")
usc09 <- read.csv("USC09.csv")
ou09 <- read.csv("OU09.csv")
texas10 <- read.csv("Texas10.csv")
tam11 <- read.csv("TAM11.csv")
usc12 <- read.csv("USC12.csv")
ark12 <- read.csv("Ark12.csv")
ugaandfla13 <- read.csv("GAandFLA13.csv")
ou14 <- read.csv("OU14.csv")
scandtam14 <- read.csv("SCandTAM14.csv")
auburn15 <- read.csv("Auburn15.csv")
michst16 <- read.csv("MichSt16.csv")
nd16 <- read.csv("ND16.csv")
fsu17 <- read.csv("FSU17.csv")
miami18 <- read.csv("Miami18.csv")
wisc18 <- read.csv("Wisc18.csv")
wash19 <- read.csv("Wash19.csv")
texas19 <- read.csv("Texas19.csv")
tam19 <- read.csv("TAM19.csv")
michst19 <- read.csv("MichSt19.csv")
psu20 <- read.csv("PSU20.csv")
isu21 <- read.csv("ISU21.csv")
nc21 <- read.csv("NC21.csv")
tam22 <- read.csv("TAM22.csv")

newbama00 <- bama00 %>% mutate(Season = "2000")
neworegst01 <- oregst01 %>% mutate(Season = "2001")
newflast01 <- flast01 %>% mutate(Season = "2001")
newnw01 <- nw01 %>% mutate(Season = "2001")
newmissst01 <- missst01 %>% mutate(Season = "2001")
newnu02 <- nu02 %>% mutate(Season = "2002")
newauburn03 <- auburn03 %>% mutate(Season = "2003")
newkst04 <- kst04 %>% mutate(Season = "2004")
newmich05 <- mich05 %>% mutate(Season = "2005")
newtenn05 <- tenn05 %>% mutate(Season = "2005")
newnd06 <- nd06 %>% mutate(Season = "2006")
newflast06 <- flast06 %>% mutate(Season = "2006")
newmich07 <- mich07 %>% mutate(Season = "2007")
newlouisville07 <- louisville07  %>% mutate(Season = "2007")
newugaandauburn08 <-ugaandauburn08 %>% mutate(Season = "2008")
newusc09 <- usc09 %>% mutate(Season = "2009")
newou09 <- ou09 %>% mutate(Season = "2009")
newtexas10 <- texas10 %>% mutate(Season = "2010")
newtam11 <- tam11 %>% mutate(Season = "2011")
newusc12 <- usc12 %>% mutate(Season = "2012")
newark12 <- ark12 %>% mutate(Season = "2012")
newugaandfla13 <- ugaandfla13 %>% mutate(Season = "2013")
newou14 <- ou14 %>% mutate(Season = "2014")
newscandtam14 <- scandtam14 %>% mutate(Season = "2014")
newauburn15 <- auburn15 %>% mutate(Season = "2015")
newmichst16 <-michst16 %>% mutate(Season = "2016")
newnd16 <- nd16 %>% mutate(Season = "2016")
newfsu17 <- fsu17 %>% mutate(Season = "2017")
newmiami18 <- miami18 %>% mutate(Season = "2018")
newwisc18 <- wisc18 %>% mutate(Season = "2018")
newwash19 <- wash19 %>% mutate(Season = "2019")
newtexas19 <- texas19 %>% mutate(Season = "2019")
newtam19 <- tam19 %>% mutate(Season = "2019")
newmichst19 <- michst19 %>% mutate(Season = "2019")
newpsu20 <- psu20 %>% mutate(Season = "2020")
newisu21 <- isu21 %>% mutate(Season = "2021")
newnc21 <- nc21 %>% mutate(Season = "2021")
newtam22 <- tam22 %>% mutate(Season = "2022")

disappointments <- bind_rows(newbama00,neworegst01,newflast01,newnw01,newmissst01,newnu02,newauburn03,newkst04,newmich05,newtenn05,newnd06,newflast06,newmich07,newlouisville07,newugaandauburn08,newusc09,newou09,newtexas10,newtam11,newusc12,newark12,newugaandfla13,newou14,newscandtam14,newauburn15,newmichst16,newnd16,newfsu17,newmiami18,newwisc18,newwash19,newtexas19,newtam19,newmichst19,newpsu20,newisu21,newnc21,newtam22)
```

```{r}
worstoftheworst <- disappointments %>% 
  filter(
    W<6
  ) %>% 
  select(Team,W,L,SRS) %>% 
  arrange(desc(W))
```

```{r}
disappointments %>% 
  summarise(
    mean(W),
    median(W),
    mean(W.1),
    median(W.1),
    mean(SRS),
    mean(AP.Pre)
  )
```

```{r}
disappointments %>% 
  filter(
    W<8,
    W.1<4,
    SRS<6.876341,
    AP.Pre<9
  )
```

```{r}
worstoftheworst %>% 
  gt() %>% 
  cols_label(
    Team = "School",
    W = "Wins",
    L = "Losses",
    SRS = "Simple Rating"
  ) %>%
  tab_header(
    title = "How does 2022 Texas A&M compare to the other biggest busts?",
    subtitle = "The Aggies subtitle goes here."
  ) %>% tab_style(
    style = cell_text(color = "black", weight = "bold", align = "left"),
    locations = cells_title("title")
  ) %>% tab_style(
    style = cell_text(color = "black", align = "left"),
    locations = cells_title("subtitle")
  ) %>%
  tab_source_note(
    source_note = md("**By:** Ryan Kenney  |  **Source:** Sports Reference")
  ) %>%
  tab_style(
     locations = cells_column_labels(columns = everything()),
     style = list(
       cell_borders(sides = "bottom", weight = px(3)),
       cell_text(weight = "bold", size=12)
     )
   ) %>%
  opt_row_striping() %>% 
  opt_table_lines("none") %>%
    
  tab_style(
    style = list(
      cell_fill(color = "#500000"),
      cell_text(color = "white")
      ),
    locations = cells_body(
      rows = Team == "Texas A&M")
  )
```
